services:
  supermarioserver:
    build:
      context: ./SuperMarioServer
    ports:
      - "3000:3000"
      - "4242-4252:4242-4252"
    container_name: supermarioserver
    restart: "no" # Simulates --rm by not restarting the container